on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.vscode/**'
      - 'docs/**'
      - 'README.md'
      - '.env.sample'
      - '.gitignore'
      - 'codecov.yml'
      - 'jest.*.js'

name: Build, Test and Coverage
jobs:
  all:
    name: Build, Test and Coverage
    runs-on: ubuntu-latest
    steps:
    # Check out repo
    - uses: actions/checkout@master

    # Cache node modules
    - name: Cache node_modules
      id: cache-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}

    # Install dependencies - use cache if possible
    - name: npm install
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: npm install

    # Run linting
    - name: lint
      run: npm run lint

    # Build package
    - name: build
      run: npm run build
    
    # Run tests and output code coverage
    - name: Test coverage
      run: npm run test:coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AZURE_DEVOPS_PROJECT_NAME: ${{ secrets.AZURE_DEVOPS_PROJECT_NAME }}
        AZURE_DEVOPS_BASE_URL: ${{ secrets.AZURE_DEVOPS_BASE_URL }}
        AZURE_DEVOPS_ACCESS_TOKEN: ${{ secrets.AZURE_DEVOPS_ACCESS_TOKEN }}
    
    # Validate code coverage using codecov.yml
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true